# goal
string output_dir
string keypoint_detection_type # either poser or mankey

RGBDWithPose[] rgbd_with_pose_list # optional, used for mug grasping
geometry_msgs/Pose T_world_rack # (optional)
---
# result
geometry_msgs/Pose T_goal_obs # goal pose
geometry_msgs/Pose T_pre_goal_obs # pre-place position
geometry_msgs/Pose T_world_gripper_fingertip # gripper fingertip to world frame

---
# feedback



